### ISSUE TITLE
F2FS broken on FUSE kernel 

### ISSUE THREAD

**Issue by a-lex-ru** [SamarV-121/android_kernel_motorola_mt6735#2]
Hello!

This kernel suffers from F2FS bug preventing normal operation of loopback devices.

Consequence: 
Magisk module installation failure
SuperSU systemless failure

The issue is affecting [LineageOS](https://samarv-121.blogspot.no/2017/11/romunofficialnicklaus-lineageos-141-for.html) as well as most recent [ResurrectionRemix](https://samarv-121.blogspot.no/2018/05/rom712unofficialstablenicklaus.html) for moto e4 plus

Tested on both.
With ResurrectionRemix the issue was tested without additional kernel installation because it is said to have latest FUSE kernel

Steps to reproduce:
Install the ROM 
(in case of Lineage, install the kernel afterwards)

reboot

install Magisk via TWRP

reboot

Attempt installing any Magisk module (Systemless Xposed for example)

Observe installation failure due to IMG mount failure.

=======

WORKAROUND

format data as EXT4 from TWRP, has to be done manually by make_ext4fs on mmcblk0p27 because TWRP's own "change filesystem type" function is not working for moto e4 plus

=======

A fix for this condition is known, but I am not knowledgeable about programming enough to submit a pull request.
The (kernel-level) fix is documented here : https://forum.xda-developers.com/showpost.php?p=70492947&postcount=8793

P.S.
[edit]
there is a fix now, and it proves problem unrelated to shutdown-slowdown issue

**Comment by SamarV-121** [comment]
https://transfer.sh/nIMbs/zImage-dtb
Replace this in Flashable zip of Fuse Kernel and flash it then tell me f2fs is fine or not

**Comment by a-lex-ru** [comment]
@SamarV-121 Just tested 

setup process:
prepare modified .zip
then
full wipe -> manual format of data into f2fs using mkfs.f2fs binary -> install lineage14 -> flash kernel  
...
**It works!**

System boots fine, magisk installs fine, magisk modules also install fine.
Problem solved

Thank you very much, Samar!

**Comment by a-lex-ru** [comment]
Also, the "magisk slowdown" issue is not related to this one.
F2FS now works  okay, and magisk slowdown still happens.

Edited to reflect this fact.

**Comment by a-lex-ru** [comment]
Was overly fast to close the issue, sorry.

Apparently, it fixes the issue on Lineage14 and RR, but not on stock.

If I use latest stock (with bootload disabled, secureboot disabled and TWRP) and flash your kernel, Magisk exhibits same mounting "disease"

But if I do flash exactly same "experimental-modified-kernel.zip" on Lineage or RR it works fine.

Mysterious.

**Comment by SamarV-121** [comment]
flash fuse kernel on stock

**Comment by a-lex-ru** [comment]
Okay, @SamarV-121 I did try both kernels (modified FUSE and "non-modified FUSE) on stock

Results are as expected - loopback is broken with normal FUSE but works okay with fixed-FUSE

the thing that bothers me is that when using stock, TWRP installation of Magisk modules fails for some odd reason.

I vaguely suspect this is due to the fact that TWRP's kernel is not fixed.

Anyway, I can confirm the F2FS fix you provided works on both stock ROM and Lineage, so I guess that's it.

I guess the issue should be closed after all now. Is this fix going into next kernel update ?

**Comment by usergb2** [comment]
@SamarV-121, this file https://transfer.sh/nIMbs/zImage-dtb is not found anymore
